### ISSUE TITLE
Sanitise input library

### ISSUE THREAD

**Issue by aanciaes** [waterdog-oss/ktor-template#13]
Might be nice to have a way to sanitise all inputs

**Comment by rmpt** [comment]
@felix19350 
just checked all of these options and there's my conclusion:
* konform
  * pros: clean setup (decoupled from domain classes), multi-platform, nice level of configuration
  * cons: doesn't seem that active, don't have i81n support, could have some more helper functions

* valiktor
  * pros: i18n support, multiple message formatters
  * cons: validation must be inserted in data objects

* kalidation
  * pros: clean setup (decoupled from domain classes), many helper functions, i18n support, active project
  * cons: not sure if it's multi-platform

I would go with kalidation. What do you think?

**Comment by felix19350** [comment]
@rmpt I agree with your assessment, multi-platform is not a requirement for this so go ahead with Kalidation
