### ISSUE TITLE
JSON Serialisation Library

### ISSUE THREAD

**Issue by aanciaes** [waterdog-oss/ktor-template#21]
Should we use Jackson or try a different one?

**Comment by felix19350** [comment]
It is probably worthwhile to test other alternatives to jackson, e.g.:

- https://github.com/google/gson
- https://github.com/square/moshi
- https://github.com/Kotlin/kotlinx.serialization

**Comment by aanciaes** [comment]
@felix19350 @monxalo @pedrohh 

### Gson (https://github.com/waterdog-oss/ktor-template/pull/36)

Gson serialiser already has a converter for ktor.
It handled well on normal kotlin classes but struggled on the generic `PageResponse <T>` deserialisation, which required a custom deserialiser to be written.
It also did not handle well kotlin's sealed classes.

### Jackson

Working fine with everything. 
As for sealed classes, instead of writing custom serialisers and deserialisers  there is a annotation for the higher sealed class that registers all subclasses and it is working fine with that, for example, with Koltin's sealed class example:

```
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type")
@JsonSubTypes(
    JsonSubTypes.Type(value = Const::class, name = "const"),
    JsonSubTypes.Type(value = Sum::class, name = "sum"),
    JsonSubTypes.Type(value = NotANumber::class, name = "notanumber")
)
sealed class Expr
data class Const(val number: Double) : Expr()
data class Sum(val e1: Expr, val e2: Expr) : Expr()
class NotANumber : Expr()
```

### Kotlinx Serialization (https://github.com/waterdog-oss/ktor-template/pull/46)

Official kotlin serialiser, already has an implemented Ktor converter. This convert seams to have an open bug ([1](https://github.com/ktorio/ktor/issues/1783), [2](https://github.com/Kotlin/kotlinx.serialization/issues/795)) that struggles to serialize the `PageResponse<T>` on the converted itself, which can for now be fixed by converting the class to string before the response being sent to the client.

All classes must be annotated with `@Serializable` so it can create custom serialisers at compile time and all koltin classes seam to be working well.

It does not automatically create third party classes serialisers, so, custom ones must be written to handled them, like java's class Instant:

```
object InstantAsStringSerializer : KSerializer<Instant> {
     override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)
     override fun serialize(encoder: Encoder, value: Instant) =
         encoder.encodeString(DateTimeFormatter.ISO_INSTANT.format(value))

     override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
 }
```
There is no centralised place to register these custom converters which means that we have to annotate these third party classes with:

```
@Serializable
data class TestInstantLongSerialization(@Serializable(with = InstantAsStringSerializer::class) val date: Instant)
```

or annotate the file that contains the class with `@file:UseSerializers(InstantAsStringSerializer::class)`

As for sealed classes, they work out of the box when annotated with the serialisable annotation.

It also has support for the nullable and default values.

### Moshi (https://github.com/waterdog-oss/ktor-template/pull/52)

Moshi does not have an out of the box converter for ktor, so a custom one must be written. A converter for ktor must be as generic as possible so it can parse any king of object and classes. I run into some problems and could not write a generic enough converter to handle the `PageResponse<T>` which means that when sending and receiving this type of classes on ktor must be done in string format and serialised and deserialised on the application with custom adapters.

Normal Kotlin classes do not need to be annotated for the serialisation be use Kotlin's reflection, but to auto generate adapters at compile time, `kapt` plugin must be enabled and all classes annotated with `@JsonClass(generateAdapter = true)`.

Like Kotlinx-serialisation, third party classes such as `Date` and `Instant` must have custom serialisers, although they are very simple to write and can all be registered in the same place (when building the Moshi Json converter).

```
class InstantAdapter {
     @ToJson
     fun toJson(instant: Instant): Long {
         return instant.toEpochMilli()
     }

     @FromJson
     fun fromJson(instant: Long): Instant {
         return Instant.ofEpochMilli(instant)
     }
 }

(...)

Moshi.Builder()
         .add(InstantAdapter())
         .build()
```

Sealed classes also have to have a custom adapter, however, there isn't a need to write them, we just need to register a custom adapter with all the subclasses:

```
Moshi.Builder()
         .add(
             PolymorphicJsonAdapterFactory.of(Expr::class.java, "exp")
                 .withSubtype(Const::class.java, "const")
                 .withSubtype(Sum::class.java, "sum")
                 .withSubtype(NotANumber::class.java, "notanumber")
         )
         .build()
```

It also has support for the nullable and default values.

### Comparison and Performance

I found a nice [blog](https://blog.usejournal.com/beyond-gson-evaluating-json-parsers-for-android-kotlin-e7aa4bcc413e) and [another one](https://medium.com/stanwood/save-my-ass-benchmark-of-json-deserializers-on-android-28341c1e82df) that compares them all with some performance testing at the end. (note: versions might not be the latest).

Test are on Android, but I think we can have a nice ideia of the performance of each library.

It seams that Kotlinx-Serialization and Moshi have similar performances when both are generating code, then we have Gson. Although Jackson seams to be the slowest, it is the most complex and complete one.
