### ISSUE TITLE
Reorganize dependencies declaration into a single file.

### ISSUE THREAD

**Issue by monxalo** [waterdog-oss/ktor-template#37]
Besides for better maintenance this would be helpful for hash calculation when using CI cache.

**Comment by felix19350** [comment]
@monxalo what do you mean by this? All the dependencies are declared in build.gradle, what am I missing?

**Comment by monxalo** [comment]
Yes, but the version number are in a separate file which calculating just the hash for that file won't reflect the updated versions but we can join the 2 files for hashing, so just an oversight from me. We can close this.

**Comment by monxalo** [comment]
Resolved with #45
