### ISSUE TITLE
Change the project structure to a multi-module project

### ISSUE THREAD

**Issue by felix19350** [waterdog-oss/ktor-template#62]
Change the project structure to a multi-module project with two modules:
- core
- database

Each module should export an artifact. The database module depends on the core.

**Comment by monxalo** [comment]
List of dependencies for reference fo each module.

### Core

- kotlin.jdk
- ktor (serverNetty, serialization, auth)
- valiktor 
- logs (logback, logbackJson, coroutinesSlf4j)

### Database
- exposed (core, dao, jdbc)
